export const ENV = {
    API_BASE_URL: process.env.NEXT_PUBLIC_API_URL,
    SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
    SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    RAZORPAY_KEY: process.env.NEXT_PUBLIC_RAZORPAY_KEY_ID,
    MAP_DEFAULT_LAT: parseFloat(process.env.NEXT_PUBLIC_DEFAULT_MAP_LAT || "28.6139"),
    MAP_DEFAULT_LNG: parseFloat(process.env.NEXT_PUBLIC_DEFAULT_MAP_LNG || "77.2090"),
    MAP_DEFAULT_ZOOM: parseInt(process.env.NEXT_PUBLIC_DEFAULT_MAP_ZOOM || "13")
}
